### ISSUE TITLE
mqtt bridge demo launch running error

### ISSUE THREAD

**Issue by chengchenglee** [groove-x/mqtt_bridge#60]
Hello 
I tried to run demo in my environment.
ubuntu 16.04
kinetic
but error shows as below.

does anyone could help?

thanks in advance!

chengbo@chengbo-VirtualBox:~/mqtt_bridge-master/src/mqtt_bridge$ roslaunch mqtt_bridge demo.launch
... logging to /home/chengbo/.ros/log/61d02a62-1633-11ec-8345-080027c3ceaa/roslaunch-chengbo-VirtualBox-10905.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

/opt/ros/kinetic/lib/python2.7/dist-packages/roslaunch/loader.py:409: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(text)
started roslaunch server http://chengbo-VirtualBox:42587/

SUMMARY
========

PARAMETERS
 * /mqtt_bridge/bridge: [{'topic_from': '...
 * /mqtt_bridge/mqtt/client/protocol: 4
 * /mqtt_bridge/mqtt/connection/host: localhost
 * /mqtt_bridge/mqtt/connection/keepalive: 60
 * /mqtt_bridge/mqtt/connection/port: 1883
 * /mqtt_bridge/mqtt/private_path: device/001
 * /rosdistro: kinetic
 * /rosversion: 1.12.17

NODES
  /
    mqtt_bridge (mqtt_bridge/mqtt_bridge_node.py)

ROS_MASTER_URI=http://localhost:11311

process[mqtt_bridge-1]: started with pid [11011]
Traceback (most recent call last):
  File "/home/chengbo/mqtt_bridge-master/src/mqtt_bridge/scripts/mqtt_bridge_node.py", line 4, in <module>
    from mqtt_bridge.app import mqtt_bridge_node
  File "/home/chengbo/mqtt_bridge-master/src/mqtt_bridge/src/mqtt_bridge/app.py", line 1, in <module>
    import inject
  File "/home/chengbo/.local/lib/python3.5/site-packages/inject/__init__.py", line 121
    _bindings: Dict[Binding, Constructor]
             ^
SyntaxError: invalid syntax
[mqtt_bridge-1] process has died [pid 11011, exit code 1, cmd /home/chengbo/mqtt_bridge-master/src/mqtt_bridge/scripts/mqtt_bridge_node.py __name:=mqtt_bridge __log:=/home/chengbo/.ros/log/61d02a62-1633-11ec-8345-080027c3ceaa/mqtt_bridge-1.log].
log file: /home/chengbo/.ros/log/61d02a62-1633-11ec-8345-080027c3ceaa/mqtt_bridge-1*.log
all processes on machine have died, roslaunch will exit
shutting down processing monitor...
... shutting down processing monitor complete
done

**Comment by chengchenglee** [comment]
I solve this question by installing the correct inject library.
